# Generated by Django 4.1.3 on 2022-12-06 12:00

from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='LibGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('published_date', models.DateTimeField(blank=True)),
                ('craft_upload', pyuploadcare.dj.models.ImageField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.libgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('image_upload', pyuploadcare.dj.models.ImageField(blank=True)),
                ('image_description', models.TextField()),
                ('image_time_created', models.DateTimeField(auto_now_add=True)),
                ('image_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lib.category')),
                ('image_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lib.location')),
            ],
            options={
                'ordering': ['image_name'],
            },
        ),
    ]
